### PR TITLE
Improved error handling. 

### PR DESCRIPTION
**Pull request by Viren070**
This improves the error handling and also shows that dinosaur for each error changing the colours to red on black.
Just read the code carefully in case I missed anything you added with the last commit

### CODE REVIEW

**Comment by S1rDyn0** [comment]
Hi, please fix errors.

There are multiple logical errors.

**Comment by S1rDyn0** [comment]
Close reason:

Code was too buggy and had several flaws.

**Comment by Viren070** [comment]
> Close reason:
> 
> Code was too buggy and had several flaws.

Test the batch script now, it works fine on my laptop.

**Comment by Viren070** [comment]
Ok wait ill add your changes and then you can merge

**Review by S1rDyn0 — CHANGES_REQUESTED** [review]
Merge Conflicts | Check main as it has major updates

**Review by Viren070 — COMMENTED** [review]
it looks alright

**Review by S1rDyn0 — APPROVED** [review]

**Pull request merged**
